# Generated by Django 4.0.4 on 2022-05-22 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voice_record", models.FileField(upload_to="audios")),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
    ]
